### ISSUE TITLE
Problem with Mean % of Area

### ISSUE THREAD

**Issue by marilink** [numeroteca/pageonex#199]
In this thread http://pageonex.com/marilink/volkswagen-in-french-press/ I see values higher than 100% as mean % of area (days 23 and 24). 

In the table you can see the number in Le Monde is 1.68 and in  Libération both of the cells show >2. If it's a mean of percentage of the total area of coverage in a home page should not be higher than 100 % I think, or is there other calculation?

**Comment by marilink** [comment]
I selected the areas again in Libération those 2 days and it seems that the problem is fixed and the calculation is correct now.

**Comment by numeroteca** [comment]
Hi Marikink, thanks for reporting this bug.

I've checked your thread and I see that all the areas are 3 times on the same place. That is the reason why you can see different shades of red and the values are so high. Areas are semitransparent, so when you see darker areas, it means that multiple areas are in the ame place. You are right, values can not be hight than 100%! 

![triple-areas](https://cloud.githubusercontent.com/assets/1223722/11326485/49c22392-916b-11e5-9efa-2787d8bfea0d.png)
Only the areas from the newspaper Libération are ok. I guess they are the ones you recoded.

I've not able to replicate the problem, but it has happened once in a while while saving a thread. Instead of saving one area it saves the same area multiple times.

I guess you'll have to recode everything (or if you are using the values in the table, divide everything by 3). We are planning to add a feature to delete specific areas to help with this kind of issues, but it is not yet developed.

Note: the bar chart displays the average of the percentages of the surface dedicated to a topic in a front page of all the available newspapers for any given day.
